react capstone project
TamaraDimov/metrics-webapp pull request #3
Opened 2023-03-21 17:22 UTC by TamaraDimov

In this project I was able to do the following:

I fetched the countries data from https://restcountries.com/

In the home page there are cards with all countries and also a dropdown menu where you can select the continents.

In the detail view if the cards, you can see the details of all countries (population, flag, capitol city, currencies and time zone.)

Additionally local time and date is shown using luxon

You can see the walkthrough video of the web app [soon.](In this project I was able to do the following:

I fetched the countries data from https://restcountries.com/

In the home page there are cards with all countries and also a dropdown menu where you can select the continents.

In the detail view if the cards, you can see the details of all countries (population, flag, capitol city, currencies and time zone.)

Additionally local time and date is shown using luxon

You can see the walkthrough video of the web app [here](https://www.loom.com/share/dac593360be441f9b8392b614c2af300)

2023-03-21 20:06 UTC, Gambit142 requested changes
Hi @TamaraDimov 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- It has a _**Home**_ and _**Details**_ Page ✔️
- Use of _**duck**_ pattern to structure files ✔️ 
- Use of redux toolkit ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-21 20:06 UTC, Gambit142 commented on README.md
> +
- [x] In the _**Acknowledgement section**_ of the README, it would be professional and lawful to give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-03-21 20:06 UTC, Gambit142 commented on src/App.css
> +  font-size: 1.2rem;
- [x] Based on the design guidelines, you ought to use `Lato` for font control and `Gill Sans` for the body or title font. It would be nice to use these fonts instead of Cabin and sans-serif. 👍 

![image](https://user-images.githubusercontent.com/77106962/226720330-8e05dfbe-dada-4886-b4c8-118f604dfd0f.png)

2023-03-21 20:06 UTC, Gambit142 commented on src/__tests__/Countries.test.js
> +});
- [x] One of the requirements for this project is to use **_React Testing Library_** to carry out integration tests for your components. Currently, you have only `react-test-renderer` to carry out snapshot tests. It would be nice to use React Testing Library. You can read this [article](https://www.freecodecamp.org/news/how-to-write-unit-tests-in-react-redux/) to learn how to use React Testing Library. It also covers integration tests with the redux toolkit. 👍 😎

2023-03-21 20:06 UTC, Gambit142 commented on src/components/Navigation.js
> +/* eslint-disable import/no-extraneous-dependencies */
- [x] Kindly remove this `Eslint-disable` statement from this file. `Eslint` helps us to write clean, maintainable and industry-standard codes and using the `Eslint-disable` statement defeats this purpose. 👍 😎

2023-03-21 20:06 UTC, Gambit142 commented on src/components/Navigation.js
> +};
- [x] Kindly make your navigation on both the `Countries` and `Detail` pages look identical to the navigation provided in the template. Remember that one of the requirements is to design your application in such a way that it has the same composition and layout. Also, kindly stick to the design requirement for the use of one **_color_**. 👍 😎 

### Your Application

![image](https://user-images.githubusercontent.com/77106962/226724931-07fc132c-a482-4475-b191-b71ab8e8c931.png)

### Behance Design

![image](https://user-images.githubusercontent.com/77106962/226725061-a0c076f9-182f-4800-998e-32b186d21cd7.png)

#### Hint: The icons displayed in the design template can be placeholders in your design. 💻

2023-03-21 20:06 UTC, Gambit142 commented on src/components/Countries.js
> +      </div>
- [ ] The top section of your design should be identical to that of the design template. Currently, you have a dropdown at the top section of your application. It would be nice to make your design look identical to that of the design template

### Your Design

![image](https://user-images.githubusercontent.com/77106962/226726090-dedd7a6d-b0e3-4abc-ba27-26bfb3285a88.png)


### Behance Design

![image](https://user-images.githubusercontent.com/77106962/226726313-5a3bab90-b307-4479-8195-cc7741866b53.png)

#### Hint: You can put the dropdown after the top section of your application.

2023-03-21 20:06 UTC, Gambit142 commented on src/components/Country.js
> +
- [OPTIONAL] For each country, it would be nice to use the **_right-arrow icon_** to indicate to a user that each country can be clicked upon to see the details page. This will improve the user interface in terms of aesthetics and the user experience in terms of navigation. 👍 😎  

### Your Design
![image](https://user-images.githubusercontent.com/77106962/226727733-5ef32948-672d-4a05-b3e8-eb0ddaf5c9fb.png)

### Behance Design

![image](https://user-images.githubusercontent.com/77106962/226727897-595edcbf-2af9-4834-86b5-6bc50b2b08bf.png)

2023-03-22 08:19 UTC, amejid requested changes
Hi @TamaraDimov, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media3.giphy.com/media/yoOotVRp4JMxVTEgDy/giphy.gif"/>

 ## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Gitflow :heavy_check_mark: 
- Functionalities working as expected :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 08:19 UTC, amejid commented on src/__tests__/Navigation.test.js
> +    expect(container).toMatchSnapshot();
- [ ] Great job working on improving the tests :+1:. This is what I'm getting when running the tests. Please update them so they are passing. 🤝️

![image](https://user-images.githubusercontent.com/17243325/226840703-248f0c32-db54-4e8e-be05-03bfc08db13a.png)

2023-03-22 09:32 UTC, Rustamxon7 approved these changes
Hi @TamaraDimov

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯
3. Perfect implementation on tests 💯 

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 11:44 UTC, merged